services:
  - type: web
    name: business-model-finder
    env: node
    plan: starter
    buildCommand: npm install && cd client && npm install --legacy-peer-deps && npm run build && cd .. && echo "✅ Build completed successfully"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: business-model-finder
          property: url
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: business-model-finder
          property: url
      - key: OPENAI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_URL
        value: https://bizmodelai.com/api/stripe/webhook
      - key: STRIPE_SIGNING_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: VITE_PAYPAL_CLIENT_ID
        sync: false
      - key: ADMIN_API_KEY
        sync: false

databases:
  - name: business-model-finder-db
    databaseName: businessmodelfinder
    user: businessmodelfinder
    plan: starter 
    healthCheckPath: /api/health
    autoDeploy: true 