import { BusinessPath } from "./types";

export const businessPaths: BusinessPath[] = [
  {
    id: "content-creation",
    name: "Content Creation / UGC",
    description:
      "Create videos, photos, blogs, or social media posts for personal brands or other businesses",
    detailedDescription:
      "Content creation and user-generated content (UGC) involve producing videos, photos, blogs, or social media posts for personal brands or other businesses. UGC creators are often paid by companies to create native-style content that aligns with the brand's identity but feels organic to viewers.",
    fitScore: 0,
    timeToProfit: "2-4 weeks",
    startupCost: "$0-300",
    potentialIncome: "$0-20K/month",
    pros: [
      "Extremely low barrier to entry",
      "Creative freedom and self-expression",
      "Potential for large income with no inventory",
      "Flexible work schedule",
      "Builds long-term personal brand equity",
      "Opens opportunities in many niches",
    ],
    cons: [
      "Algorithms can change rapidly",
      "Time-intensive content planning and editing",
      "Emotional toll of public feedback",
      "Inconsistent income early on",
      "High competition and saturation",
      "Burnout is common without balance",
    ],
    tools: ["CapCut", "Canva", "TikTok", "Instagram", "Notion"],
    skills: [
      "Creative thinking",
      "Communication",
      "Social media",
      "Visual storytelling",
      "Trend awareness",
    ],
    icon: "TrendingUp",
    emoji: "🚀",
    marketSize: "Creator economy valued at over $104B",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-20K/month",
    },
    userStruggles: [
      "Consistency challenges",
      "Audience growth",
      "Monetization timing",
      "Negative feedback handling",
    ],
    solutions: [
      "Content calendar planning",
      "Focus on niche audience",
      "Diversify revenue streams",
      "Build thick skin and community",
    ],
    bestFitPersonality: [
      "Creative and innovative",
      "Patient and persistent",
      "Comfortable on camera",
      "Resilient to criticism",
    ],
    resources: {
      platforms: ["YouTube", "TikTok", "Instagram", "Creator Now"],
      learning: ["YouTube Creator Academy", "Creator economy courses"],
      tools: ["CapCut", "Canva", "Later", "Notion"],
    },
    actionPlan: {
      phase1: [
        "Choose content niche",
        "Set up equipment",
        "Create content calendar",
        "Post consistently",
      ],
      phase2: [
        "Engage with audience",
        "Collaborate with others",
        "Optimize for algorithms",
        "Track analytics",
      ],
      phase3: [
        "Monetize through ads",
        "Secure sponsorships",
        "Launch own products",
        "Expand to new platforms",
      ],
    },
  },
  {
    id: "freelancing",
    name: "Freelancing",
    description:
      "Offer specialized services to clients on a project or contract basis",
    detailedDescription:
      "Freelancing involves offering specialized services to clients on a project or contract basis. This could include writing, graphic design, web development, marketing, consulting, or any skill-based service. Freelancers work independently, often with multiple clients, and have the flexibility to choose their projects and set their rates.",
    fitScore: 0,
    timeToProfit: "1-2 weeks",
    startupCost: "$0-500",
    potentialIncome: "$1K-15K+/month",
    pros: [
      "Quick to start with existing skills",
      "Complete schedule flexibility",
      "Choose your own clients and projects",
      "No inventory or upfront costs",
      "Can work from anywhere",
      "Direct relationship with income and effort",
    ],
    cons: [
      "Income can be inconsistent",
      "No benefits or job security",
      "Constant client acquisition needed",
      "Time-for-money limitation",
      "Handling all business aspects alone",
      "Potential for scope creep and difficult clients",
    ],
    tools: ["Upwork", "Fiverr", "LinkedIn", "Slack", "Zoom"],
    skills: [
      "Specialized expertise",
      "Client communication",
      "Project management",
      "Time management",
      "Networking",
    ],
    icon: "Briefcase",
    emoji: "🧑‍💻",
    marketSize: "Freelance economy worth $400B+ globally",
    averageIncome: {
      beginner: "$500-2K/month",
      intermediate: "$2K-8K/month",
      advanced: "$8K-15K+/month",
    },
    userStruggles: [
      "Finding consistent clients",
      "Pricing services appropriately",
      "Managing multiple projects",
      "Dealing with difficult clients",
    ],
    solutions: [
      "Build strong portfolio and testimonials",
      "Develop recurring client relationships",
      "Use project management tools",
      "Set clear boundaries and contracts",
    ],
    bestFitPersonality: [
      "Self-motivated and disciplined",
      "Strong communication skills",
      "Adaptable to different clients",
      "Business-minded",
    ],
    resources: {
      platforms: ["Upwork", "Fiverr", "LinkedIn", "Freelancer"],
      learning: ["Freelancer courses", "Industry certifications"],
      tools: ["Slack", "Zoom", "Trello", "FreshBooks"],
    },
    actionPlan: {
      phase1: [
        "Identify your skills",
        "Create portfolio",
        "Set up profiles on platforms",
        "Apply for first projects",
      ],
      phase2: [
        "Deliver quality work",
        "Collect testimonials",
        "Raise your rates",
        "Build repeat clients",
      ],
      phase3: [
        "Specialize in high-value niches",
        "Create passive income streams",
        "Build a personal brand",
        "Consider hiring subcontractors",
      ],
    },
  },
  {
    id: "affiliate-marketing",
    name: "Affiliate Marketing",
    description:
      "Promote other companies' products and earn commissions on successful referrals",
    detailedDescription:
      "Affiliate marketing involves promoting other companies' products or services and earning a commission for each sale or lead generated through your referral. This can be done through blogs, social media, email marketing, or paid advertising.",
    fitScore: 0,
    timeToProfit: "3-6 months",
    startupCost: "$0-1000",
    potentialIncome: "$0-50K+/month",
    pros: [
      "No product creation required",
      "Passive income potential",
      "Low startup costs",
      "Flexible schedule",
      "Scalable income",
      "Work from anywhere",
    ],
    cons: [
      "Takes time to build audience",
      "Dependent on other companies",
      "Commission-based income",
      "High competition",
      "Need to constantly adapt to changes",
      "Building trust takes time",
    ],
    tools: [
      "WordPress",
      "ConvertKit",
      "Google Analytics",
      "Canva",
      "Social media platforms",
    ],
    skills: [
      "Content creation",
      "SEO",
      "Email marketing",
      "Social media marketing",
      "Analytics",
    ],
    icon: "TrendingUp",
    emoji: "🔗",
    marketSize: "Affiliate marketing industry worth $17B+ globally",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-50K+/month",
    },
    userStruggles: [
      "Building initial audience",
      "Finding profitable niches",
      "Creating engaging content",
      "Tracking and optimizing campaigns",
    ],
    solutions: [
      "Focus on one niche initially",
      "Provide genuine value first",
      "Use analytics to optimize",
      "Build email list early",
    ],
    bestFitPersonality: [
      "Patient and persistent",
      "Good at building relationships",
      "Analytical mindset",
      "Marketing-oriented",
    ],
    resources: {
      platforms: [
        "Amazon Associates",
        "ShareASale",
        "CJ Affiliate",
        "ClickBank",
      ],
      learning: ["Affiliate marketing courses", "Industry blogs"],
      tools: ["WordPress", "ConvertKit", "Google Analytics", "Canva"],
    },
    actionPlan: {
      phase1: [
        "Choose your niche",
        "Research affiliate programs",
        "Create content platform",
        "Start creating valuable content",
      ],
      phase2: [
        "Build email list",
        "Join affiliate programs",
        "Create product reviews",
        "Optimize for SEO",
      ],
      phase3: [
        "Scale successful campaigns",
        "Diversify income streams",
        "Build personal brand",
        "Consider paid advertising",
      ],
    },
  },
  {
    id: "online-coaching",
    name: "Online Coaching",
    description:
      "Provide expertise and guidance to clients in your area of specialization",
    detailedDescription:
      "Online coaching involves providing expertise, guidance, and strategic advice to clients in your area of specialization. This could range from business consulting to life coaching, fitness training, or career guidance. Sessions are typically conducted via video calls, and packages can include one-on-one sessions, group coaching, or digital courses.",
    fitScore: 0,
    timeToProfit: "1-2 weeks",
    startupCost: "$0-200",
    potentialIncome: "$1K-10K/month",
    pros: [
      "Use existing knowledge and skills",
      "Flexible scheduling",
      "High hourly rates possible",
      "Rewarding work helping others",
      "No inventory needed",
      "Global student reach",
    ],
    cons: [
      "Time-for-money limitation",
      "Seasonal demand variations",
      "Need to manage difficult students",
      "Preparation time required",
      "Competition from platforms",
      "Inconsistent income",
    ],
    tools: ["Zoom", "Google Meet", "Teachable", "Udemy", "Calendly"],
    skills: [
      "Subject expertise",
      "Teaching ability",
      "Patience",
      "Communication",
      "Technology",
    ],
    icon: "BookOpen",
    emoji: "🧑‍💼",
    marketSize: "Online tutoring market worth $15B+ globally",
    averageIncome: {
      beginner: "$500-2K/month",
      intermediate: "$2K-5K/month",
      advanced: "$5K-10K/month",
    },
    userStruggles: [
      "Finding students initially",
      "Setting appropriate rates",
      "Managing scheduling",
      "Handling payment processing",
    ],
    solutions: [
      "Join established platforms first",
      "Create valuable free content",
      "Build student testimonials",
      "Use scheduling tools",
    ],
    bestFitPersonality: [
      "Patient and encouraging",
      "Clear communicator",
      "Subject matter expert",
      "Enjoys helping others",
    ],
    resources: {
      platforms: ["Wyzant", "Tutor.com", "Preply", "iTalki"],
      learning: ["Teaching certification courses", "Online education training"],
      tools: ["Zoom", "Google Meet", "Calendly", "PayPal"],
    },
    actionPlan: {
      phase1: [
        "Define your expertise area",
        "Create tutor profiles",
        "Set competitive rates",
        "Get first students",
      ],
      phase2: [
        "Build reputation and reviews",
        "Increase rates gradually",
        "Develop teaching materials",
        "Expand subject areas",
      ],
      phase3: [
        "Create online courses",
        "Build personal brand",
        "Hire other tutors",
        "Launch tutoring agency",
      ],
    },
  },
  {
    id: "e-commerce",
    name: "E-commerce Store",
    description:
      "Sell physical or digital products online through your own store",
    detailedDescription:
      "E-commerce involves creating an online store to sell products directly to consumers. This can include physical products, digital downloads, print-on-demand items, or dropshipping products from suppliers.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "2-6 months",
    startupCost: "$500-5K",
    potentialIncome: "$1K-100K+/month",
    pros: [
      "Scalable business model",
      "Passive income potential",
      "Global customer reach",
      "Multiple revenue streams",
      "Build valuable asset",
      "Creative product control",
    ],
    cons: [
      "High initial investment",
      "Inventory management",
      "Customer service demands",
      "Marketing costs",
      "Competition pressure",
      "Technical complexity",
    ],
    tools: [
      "Shopify",
      "WooCommerce",
      "Facebook Ads",
      "Google Analytics",
      "Klaviyo",
    ],
    skills: [
      "Digital marketing",
      "Product sourcing",
      "Customer service",
      "Analytics",
      "Design",
    ],
    icon: "Star",
    emoji: "🛒",
    marketSize: "Global e-commerce worth $6.2T+ annually",
    averageIncome: {
      beginner: "$0-2K/month",
      intermediate: "$2K-15K/month",
      advanced: "$15K-100K+/month",
    },
    userStruggles: [
      "Finding profitable products",
      "Driving traffic to store",
      "Managing inventory",
      "Converting visitors to sales",
    ],
    solutions: [
      "Start with validated products",
      "Focus on SEO and content marketing",
      "Use inventory management tools",
      "Optimize conversion funnel",
    ],
    bestFitPersonality: [
      "Entrepreneurial mindset",
      "Detail-oriented",
      "Marketing-focused",
      "Customer-centric",
    ],
    resources: {
      platforms: ["Shopify", "WooCommerce", "BigCommerce", "Etsy"],
      learning: ["E-commerce courses", "Dropshipping guides"],
      tools: ["Shopify", "Facebook Ads", "Google Analytics", "Klaviyo"],
    },
    actionPlan: {
      phase1: [
        "Research product niches",
        "Set up online store",
        "Source initial products",
        "Create product listings",
      ],
      phase2: [
        "Launch marketing campaigns",
        "Optimize store conversion",
        "Build customer base",
        "Expand product line",
      ],
      phase3: [
        "Scale advertising spend",
        "Develop private label products",
        "Build brand loyalty",
        "Explore new markets",
      ],
    },
  },
  {
    id: "youtube-automation",
    name: "YouTube Automation",
    description:
      "Create and monetize YouTube channels with minimal personal involvement",
    detailedDescription:
      "YouTube automation involves creating YouTube channels that generate revenue through systematic content creation, often using outsourced creators, stock footage, or AI tools to minimize personal time investment.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "3-6 months",
    startupCost: "$500-2K",
    potentialIncome: "$1K-50K+/month",
    pros: [
      "Passive income potential",
      "Scalable to multiple channels",
      "No need to be on camera",
      "Multiple monetization methods",
      "Global audience reach",
      "Long-term asset building",
    ],
    cons: [
      "Algorithm dependency",
      "High competition",
      "Initial investment required",
      "Time to build audience",
      "Content creation challenges",
      "Platform policy changes",
    ],
    tools: ["TubeBuddy", "VidIQ", "Canva", "AI voice tools", "Stock footage"],
    skills: [
      "Video editing",
      "SEO optimization",
      "Market research",
      "Analytics",
      "Outsourcing",
    ],
    icon: "Play",
    emoji: "📺",
    marketSize: "YouTube ad revenue over $28B+ annually",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-50K+/month",
    },
    userStruggles: [
      "Finding profitable niches",
      "Creating engaging content",
      "Managing outsourced team",
      "Maintaining consistent uploads",
    ],
    solutions: [
      "Research trending topics",
      "Study successful channels",
      "Use project management tools",
      "Create content calendars",
    ],
    bestFitPersonality: [
      "Business-minded",
      "Patient with long-term goals",
      "Good at delegation",
      "Analytical thinker",
    ],
    resources: {
      platforms: ["YouTube Studio", "TubeBuddy", "VidIQ"],
      learning: ["YouTube automation courses", "Video marketing guides"],
      tools: ["TubeBuddy", "VidIQ", "Canva", "Murf AI"],
    },
    actionPlan: {
      phase1: [
        "Research profitable niches",
        "Create channel and branding",
        "Develop content strategy",
        "Upload first videos",
      ],
      phase2: [
        "Optimize for YouTube SEO",
        "Build outsourcing team",
        "Scale content production",
        "Apply for monetization",
      ],
      phase3: [
        "Launch multiple channels",
        "Diversify revenue streams",
        "Build automation systems",
        "Scale to 6-figure business",
      ],
    },
  },
  {
    id: "local-service",
    name: "Local Service Business",
    description:
      "Provide services to businesses and residents in your local area",
    detailedDescription:
      "Local service businesses provide essential services to nearby businesses and homeowners, such as cleaning, lawn care, handyman services, pet care, or professional services like accounting or consulting.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-4 weeks",
    startupCost: "$100-2K",
    potentialIncome: "$2K-20K/month",
    pros: [
      "Quick to start earning",
      "Recurring customer relationships",
      "Lower competition online",
      "Cash-based transactions",
      "Personal relationships",
      "Essential service demand",
    ],
    cons: [
      "Limited to local market",
      "Physical presence required",
      "Weather/seasonal factors",
      "Equipment and vehicle needs",
      "Time-intensive work",
      "Limited scalability",
    ],
    tools: [
      "Google My Business",
      "Nextdoor",
      "Square",
      "QuickBooks",
      "Scheduling apps",
    ],
    skills: [
      "Service expertise",
      "Customer service",
      "Local marketing",
      "Operations",
      "Reliability",
    ],
    icon: "Target",
    emoji: "🛠️",
    marketSize: "Local services market worth $500B+ in US",
    averageIncome: {
      beginner: "$1K-3K/month",
      intermediate: "$3K-8K/month",
      advanced: "$8K-20K/month",
    },
    userStruggles: [
      "Finding first customers",
      "Pricing services competitively",
      "Managing scheduling",
      "Scaling beyond personal time",
    ],
    solutions: [
      "Start with friends and neighbors",
      "Research local competitor pricing",
      "Use scheduling software",
      "Hire help as you grow",
    ],
    bestFitPersonality: [
      "Enjoys hands-on work",
      "Good with people",
      "Reliable and trustworthy",
      "Community-oriented",
    ],
    resources: {
      platforms: ["Google My Business", "Nextdoor", "TaskRabbit", "Thumbtack"],
      learning: ["Local business guides", "Service industry training"],
      tools: ["Google My Business", "Square", "QuickBooks", "Calendly"],
    },
    actionPlan: {
      phase1: [
        "Define your service offering",
        "Get necessary licenses/insurance",
        "Create Google My Business",
        "Get first customers",
      ],
      phase2: [
        "Build customer reviews",
        "Expand service offerings",
        "Implement booking system",
        "Increase rates gradually",
      ],
      phase3: [
        "Hire additional workers",
        "Expand service area",
        "Add complementary services",
        "Build referral system",
      ],
    },
  },
  {
    id: "high-ticket-sales",
    name: "High-Ticket Sales",
    description:
      "Sell premium products or services with substantial commission potential",
    detailedDescription:
      "High-ticket sales involves selling expensive products or services, typically involving consultative sales processes, relationship building, and substantial per-transaction earnings. This can include real estate, luxury goods, B2B software, or coaching programs.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "2-6 months",
    startupCost: "$0-1K",
    potentialIncome: "$5K-100K+/month",
    pros: [
      "High earnings per sale",
      "Relationship-based business",
      "Skills transfer to many industries",
      "Performance-based rewards",
      "Professional development",
      "Network building opportunities",
    ],
    cons: [
      "Inconsistent income timing",
      "High rejection rates",
      "Pressure and stress",
      "Long sales cycles",
      "Requires thick skin",
      "Performance accountability",
    ],
    tools: [
      "CRM software",
      "LinkedIn Sales Navigator",
      "Zoom",
      "Email automation",
      "Calendly",
    ],
    skills: [
      "Communication",
      "Relationship building",
      "Negotiation",
      "Psychology",
      "Persistence",
    ],
    icon: "TrendingUp",
    emoji: "🤝",
    marketSize: "B2B sales market worth $6T+ globally",
    averageIncome: {
      beginner: "$2K-8K/month",
      intermediate: "$8K-25K/month",
      advanced: "$25K-100K+/month",
    },
    userStruggles: [
      "Handling rejection",
      "Building initial pipeline",
      "Closing complex deals",
      "Managing long sales cycles",
    ],
    solutions: [
      "Focus on relationship building",
      "Use consultative selling approach",
      "Track metrics and optimize",
      "Continuous learning and practice",
    ],
    bestFitPersonality: [
      "Excellent communicator",
      "Resilient to rejection",
      "Goal-oriented",
      "Enjoys helping others",
    ],
    resources: {
      platforms: ["LinkedIn", "Salesforce", "HubSpot"],
      learning: ["Sales training courses", "Industry certifications"],
      tools: ["CRM software", "LinkedIn Sales Navigator", "Calendly"],
    },
    actionPlan: {
      phase1: [
        "Choose your industry",
        "Learn product knowledge",
        "Set up CRM system",
        "Start prospecting",
      ],
      phase2: [
        "Build sales pipeline",
        "Refine sales process",
        "Track and optimize metrics",
        "Close first deals",
      ],
      phase3: [
        "Scale prospecting efforts",
        "Build referral network",
        "Mentor other sales reps",
        "Consider leadership roles",
      ],
    },
  },
  {
    id: "saas-development",
    name: "SaaS Development",
    description:
      "Build software applications that generate recurring subscription revenue",
    detailedDescription:
      "SaaS (Software as a Service) development involves creating web applications that solve specific problems for businesses or consumers, generating recurring revenue through subscription models.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "6-18 months",
    startupCost: "$500-5K",
    potentialIncome: "$1K-500K+/month",
    pros: [
      "Recurring revenue model",
      "Highly scalable business",
      "High profit margins",
      "Global market reach",
      "Valuable asset creation",
      "Solving real problems",
    ],
    cons: [
      "High technical barriers",
      "Long development time",
      "Competitive market",
      "Ongoing maintenance costs",
      "Customer churn challenges",
      "Significant upfront investment",
    ],
    tools: ["AWS", "React", "Node.js", "Stripe", "Analytics tools"],
    skills: [
      "Programming",
      "Product management",
      "UI/UX design",
      "Marketing",
      "Customer support",
    ],
    icon: "Monitor",
    emoji: "💻",
    marketSize: "Global SaaS market worth $300B+ annually",
    averageIncome: {
      beginner: "$0-2K/month",
      intermediate: "$2K-25K/month",
      advanced: "$25K-500K+/month",
    },
    userStruggles: [
      "Finding product-market fit",
      "Technical development challenges",
      "Customer acquisition costs",
      "Managing development timeline",
    ],
    solutions: [
      "Start with MVP and iterate",
      "Use no-code tools initially",
      "Focus on customer feedback",
      "Build in public for accountability",
    ],
    bestFitPersonality: [
      "Technical problem solver",
      "Patient with long-term goals",
      "Customer-focused",
      "Enjoys continuous learning",
    ],
    resources: {
      platforms: ["AWS", "Vercel", "Stripe", "Firebase"],
      learning: ["Coding bootcamps", "SaaS development courses"],
      tools: ["React", "Node.js", "PostgreSQL", "Stripe"],
    },
    actionPlan: {
      phase1: [
        "Validate business idea",
        "Learn required technologies",
        "Build MVP version",
        "Get first beta users",
      ],
      phase2: [
        "Implement user feedback",
        "Add payment processing",
        "Focus on user acquisition",
        "Optimize conversion funnel",
      ],
      phase3: [
        "Scale marketing efforts",
        "Add advanced features",
        "Build team as needed",
        "Consider investment/exit",
      ],
    },
  },
  {
    id: "social-media-agency",
    name: "Social Media Marketing Agency",
    description:
      "Help businesses grow their online presence through social media management",
    detailedDescription:
      "Social media marketing agencies provide comprehensive social media services to businesses, including content creation, account management, advertising campaigns, and strategy development across various platforms.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "1-3 months",
    startupCost: "$500-2K",
    potentialIncome: "$3K-50K+/month",
    pros: [
      "High demand service",
      "Recurring monthly revenue",
      "Creative and strategic work",
      "Scalable business model",
      "Work with diverse clients",
      "Remote work friendly",
    ],
    cons: [
      "Keeping up with algorithm changes",
      "Client management challenges",
      "Competitive market",
      "Proving ROI pressure",
      "Time-intensive content creation",
      "Platform dependency",
    ],
    tools: [
      "Hootsuite",
      "Canva",
      "Facebook Ads Manager",
      "Analytics tools",
      "Scheduling software",
    ],
    skills: [
      "Social media marketing",
      "Content creation",
      "Analytics",
      "Client management",
      "Design",
    ],
    icon: "Users",
    emoji: "📣",
    marketSize: "Social media marketing worth $150B+ globally",
    averageIncome: {
      beginner: "$2K-5K/month",
      intermediate: "$5K-15K/month",
      advanced: "$15K-50K+/month",
    },
    userStruggles: [
      "Finding quality clients",
      "Proving measurable results",
      "Managing multiple accounts",
      "Staying current with trends",
    ],
    solutions: [
      "Specialize in specific niches",
      "Create detailed reporting systems",
      "Use management tools",
      "Continuous learning and adaptation",
    ],
    bestFitPersonality: [
      "Creative and strategic",
      "Excellent communicator",
      "Detail-oriented",
      "Adaptable to change",
    ],
    resources: {
      platforms: ["Facebook", "Instagram", "LinkedIn", "TikTok"],
      learning: ["Social media marketing courses", "Platform certifications"],
      tools: ["Hootsuite", "Buffer", "Canva", "Google Analytics"],
    },
    actionPlan: {
      phase1: [
        "Learn social media platforms",
        "Create portfolio content",
        "Get first clients",
        "Set up management tools",
      ],
      phase2: [
        "Develop service packages",
        "Build case studies",
        "Scale client base",
        "Optimize processes",
      ],
      phase3: [
        "Hire team members",
        "Expand service offerings",
        "Build agency brand",
        "Target larger clients",
      ],
    },
  },
  {
    id: "ai-marketing-agency",
    name: "AI Marketing Agency",
    description:
      "Leverage AI tools to provide cutting-edge marketing solutions for businesses",
    detailedDescription:
      "AI marketing agencies use artificial intelligence tools and technologies to provide advanced marketing services, including automated content creation, predictive analytics, chatbots, and AI-powered advertising optimization.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "2-6 months",
    startupCost: "$1K-5K",
    potentialIncome: "$5K-100K+/month",
    pros: [
      "Cutting-edge technology advantage",
      "High-value service offering",
      "Scalable with automation",
      "Premium pricing potential",
      "Growing market demand",
      "Competitive differentiation",
    ],
    cons: [
      "Steep learning curve",
      "Rapidly changing technology",
      "High client expectations",
      "Technical complexity",
      "Tool subscription costs",
      "Need for continuous learning",
    ],
    tools: [
      "OpenAI API",
      "Claude",
      "Midjourney",
      "Marketing automation platforms",
      "Analytics tools",
    ],
    skills: [
      "AI tool mastery",
      "Marketing strategy",
      "Data analysis",
      "Technical integration",
      "Client education",
    ],
    icon: "Brain",
    emoji: "🤖",
    marketSize: "AI marketing market projected $100B+ by 2030",
    averageIncome: {
      beginner: "$3K-8K/month",
      intermediate: "$8K-25K/month",
      advanced: "$25K-100K+/month",
    },
    userStruggles: [
      "Keeping up with AI developments",
      "Educating clients on AI value",
      "Integration complexity",
      "Proving AI effectiveness",
    ],
    solutions: [
      "Focus on specific AI tools",
      "Create educational content",
      "Start with simple implementations",
      "Track and share success metrics",
    ],
    bestFitPersonality: [
      "Tech-savvy and innovative",
      "Continuous learner",
      "Strategic thinker",
      "Early adopter mindset",
    ],
    resources: {
      platforms: ["OpenAI", "Anthropic", "Midjourney", "HubSpot"],
      learning: ["AI marketing courses", "Technical documentation"],
      tools: ["OpenAI API", "Marketing automation", "Analytics platforms"],
    },
    actionPlan: {
      phase1: [
        "Master key AI tools",
        "Create AI-powered demos",
        "Educate potential clients",
        "Land first projects",
      ],
      phase2: [
        "Develop service frameworks",
        "Build case studies",
        "Scale AI implementations",
        "Increase pricing",
      ],
      phase3: [
        "Create proprietary AI solutions",
        "Build specialized team",
        "Target enterprise clients",
        "Consider productization",
      ],
    },
  },
  {
    id: "digital-services",
    name: "Digital Services",
    emoji: "💻",
    description:
      "Provide specialized digital services like web development, design, or consulting",
    detailedDescription:
      "Digital services encompass a wide range of technology-based services including web development, graphic design, digital marketing, SEO, content writing, and various forms of digital consulting.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "1-3 months",
    startupCost: "$0-1K",
    potentialIncome: "$2K-30K+/month",
    pros: [
      "High demand for digital skills",
      "Work from anywhere",
      "Diverse service options",
      "Scalable pricing",
      "Build valuable portfolio",
      "Continuous learning opportunities",
    ],
    cons: [
      "High competition",
      "Keeping skills current",
      "Client acquisition challenges",
      "Time-for-money limitation",
      "Scope creep issues",
      "Technology changes rapidly",
    ],
    tools: [
      "Adobe Creative Suite",
      "Figma",
      "WordPress",
      "Google Analytics",
      "Project management tools",
    ],
    skills: [
      "Technical expertise",
      "Design thinking",
      "Client communication",
      "Project management",
      "Marketing",
    ],
    icon: "🖥️",
    marketSize: "Digital services market worth $500B+ globally",
    averageIncome: {
      beginner: "$1K-3K/month",
      intermediate: "$3K-10K/month",
      advanced: "$10K-30K+/month",
    },
    userStruggles: [
      "Standing out in crowded market",
      "Pricing services appropriately",
      "Managing project scope",
      "Finding quality clients",
    ],
    solutions: [
      "Specialize in specific niches",
      "Build strong portfolio",
      "Use clear contracts",
      "Focus on relationship building",
    ],
    bestFitPersonality: [
      "Technical problem solver",
      "Detail-oriented",
      "Client-focused",
      "Adaptable to new technologies",
    ],
    resources: {
      platforms: ["Upwork", "Fiverr", "99designs", "Toptal"],
      learning: ["Online courses", "Technical certifications"],
      tools: ["Adobe CC", "Figma", "VS Code", "Project management software"],
    },
    actionPlan: {
      phase1: [
        "Choose your specialization",
        "Build portfolio projects",
        "Set up business profiles",
        "Get first clients",
      ],
      phase2: [
        "Refine service offerings",
        "Increase rates gradually",
        "Build client testimonials",
        "Expand skill set",
      ],
      phase3: [
        "Develop premium services",
        "Build agency team",
        "Create passive income streams",
        "Focus on high-value clients",
      ],
    },
  },
  {
    id: "investing-trading",
    name: "Investing & Trading",
    emoji: "💹",
    description:
      "Generate returns through strategic investment in various financial instruments",
    detailedDescription:
      "Investing and trading involves generating returns through strategic investment in stocks, cryptocurrency, real estate, forex, or other financial instruments using analysis, market timing, and risk management strategies.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "3-12 months",
    startupCost: "$1K-10K+",
    potentialIncome: "$500-unlimited/month",
    pros: [
      "Potentially unlimited returns",
      "Passive income opportunity",
      "Work from anywhere",
      "Scalable with capital",
      "Market independence",
      "Financial education benefits",
    ],
    cons: [
      "High risk of losses",
      "Requires significant capital",
      "Emotional stress",
      "Market volatility",
      "Steep learning curve",
      "No guaranteed income",
    ],
    tools: [
      "Trading platforms",
      "Charting software",
      "News feeds",
      "Portfolio trackers",
      "Risk management tools",
    ],
    skills: [
      "Market analysis",
      "Risk management",
      "Emotional control",
      "Research",
      "Mathematical thinking",
    ],
    icon: "📈",
    marketSize: "Global trading volume $6T+ daily",
    averageIncome: {
      beginner: "$0-1K/month (high variance)",
      intermediate: "$1K-5K/month (high variance)",
      advanced: "$5K-unlimited/month (high variance)",
    },
    userStruggles: [
      "Managing emotions and psychology",
      "Risk management",
      "Information overload",
      "Consistency in profits",
    ],
    solutions: [
      "Start with paper trading",
      "Develop strict risk rules",
      "Focus on education first",
      "Use systematic approaches",
    ],
    bestFitPersonality: [
      "Analytical and disciplined",
      "Comfortable with risk",
      "Emotionally stable",
      "Continuous learner",
    ],
    resources: {
      platforms: [
        "Robinhood",
        "E*TRADE",
        "TD Ameritrade",
        "Interactive Brokers",
      ],
      learning: ["Financial education courses", "Market analysis training"],
      tools: [
        "TradingView",
        "Bloomberg Terminal",
        "Portfolio management software",
      ],
    },
    actionPlan: {
      phase1: [
        "Learn market fundamentals",
        "Practice with paper trading",
        "Develop trading strategy",
        "Start with small amounts",
      ],
      phase2: [
        "Refine risk management",
        "Track performance metrics",
        "Gradually increase capital",
        "Diversify strategies",
      ],
      phase3: [
        "Scale successful strategies",
        "Consider alternative investments",
        "Potentially manage others' money",
        "Build investment business",
      ],
    },
  },
  {
    id: "copywriting",
    name: "Copywriting",
    emoji: "✍️",
    description:
      "Write persuasive marketing and sales copy for businesses and brands",
    detailedDescription:
      "Copywriting involves creating persuasive written content for businesses, including sales pages, email campaigns, advertisements, website copy, and marketing materials designed to drive specific actions from readers.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "1-3 months",
    startupCost: "$0-500",
    potentialIncome: "$2K-25K+/month",
    pros: [
      "High-value skill in demand",
      "Work from anywhere",
      "Results-driven pricing",
      "Multiple industries to serve",
      "Scalable income potential",
      "Creative and strategic work",
    ],
    cons: [
      "Pressure to deliver results",
      "Competitive market",
      "Client education needed",
      "Income can be project-based",
      "Constant need to prove ROI",
      "Writing skills must be excellent",
    ],
    tools: [
      "Google Docs",
      "Grammarly",
      "Hemingway Editor",
      "Research tools",
      "Project management",
    ],
    skills: [
      "Persuasive writing",
      "Psychology",
      "Market research",
      "A/B testing",
      "Client communication",
    ],
    icon: "✒️",
    marketSize: "Content marketing industry worth $400B+ globally",
    averageIncome: {
      beginner: "$1K-3K/month",
      intermediate: "$3K-10K/month",
      advanced: "$10K-25K+/month",
    },
    userStruggles: [
      "Finding clients who value copy",
      "Proving copy effectiveness",
      "Handling revisions and feedback",
      "Pricing work appropriately",
    ],
    solutions: [
      "Focus on results-driven niches",
      "Track and share conversion data",
      "Set clear revision limits",
      "Charge based on value delivered",
    ],
    bestFitPersonality: [
      "Excellent writer",
      "Persuasive communicator",
      "Research-oriented",
      "Results-focused",
    ],
    resources: {
      platforms: ["Upwork", "Contently", "ClearVoice", "ProBlogger"],
      learning: ["Copywriting courses", "Marketing psychology"],
      tools: ["Google Docs", "Grammarly", "CoSchedule Headline Analyzer"],
    },
    actionPlan: {
      phase1: [
        "Learn copywriting fundamentals",
        "Create sample copy portfolio",
        "Join freelance platforms",
        "Get first clients",
      ],
      phase2: [
        "Specialize in profitable niches",
        "Track conversion results",
        "Raise rates based on results",
        "Build case studies",
      ],
      phase3: [
        "Develop premium packages",
        "Build personal brand",
        "Create copywriting courses",
        "Consider agency model",
      ],
    },
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    description:
      "Provide remote administrative, technical, or creative support to businesses",
    detailedDescription:
      "Virtual assistants provide remote support services to entrepreneurs and businesses, including administrative tasks, customer service, social media management, content creation, and specialized technical services.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-2 weeks",
    startupCost: "$0-300",
    potentialIncome: "$1K-8K/month",
    pros: [
      "Low barrier to entry",
      "Flexible schedule",
      "Diverse task variety",
      "Learn new business skills",
      "Stable recurring income",
      "Remote work opportunity",
    ],
    cons: [
      "Can be task-intensive",
      "Time zone coordination",
      "Lower hourly rates initially",
      "Client dependency",
      "Administrative workload",
      "Limited growth potential",
    ],
    tools: [
      "Slack",
      "Zoom",
      "Trello",
      "Google Workspace",
      "Time tracking software",
    ],
    skills: [
      "Organization",
      "Communication",
      "Technical proficiency",
      "Problem-solving",
      "Reliability",
    ],
    icon: "Users",
    emoji: "👥",
    marketSize: "Virtual assistant market worth $25B+ globally",
    averageIncome: {
      beginner: "$800-2K/month",
      intermediate: "$2K-5K/month",
      advanced: "$5K-8K/month",
    },
    userStruggles: [
      "Finding quality clients",
      "Setting boundaries",
      "Managing multiple clients",
      "Increasing rates over time",
    ],
    solutions: [
      "Specialize in valuable skills",
      "Set clear work agreements",
      "Use project management tools",
      "Focus on results and value",
    ],
    bestFitPersonality: [
      "Highly organized",
      "Detail-oriented",
      "Reliable and trustworthy",
      "Adaptable to different needs",
    ],
    resources: {
      platforms: ["Belay", "Time Etc", "Fancy Hands", "Upwork"],
      learning: ["VA training courses", "Business skills development"],
      tools: ["Google Workspace", "Slack", "Asana", "Calendly"],
    },
    actionPlan: {
      phase1: [
        "Identify your skill strengths",
        "Create professional profiles",
        "Apply to VA platforms",
        "Get first clients",
      ],
      phase2: [
        "Deliver exceptional service",
        "Build client testimonials",
        "Specialize in high-value tasks",
        "Increase hourly rates",
      ],
      phase3: [
        "Build VA agency",
        "Hire other VAs",
        "Create specialized services",
        "Focus on premium clients",
      ],
    },
  },
  {
    id: "online-reselling",
    name: "Online Reselling",
    emoji: "📦",
    description:
      "Buy and resell products online through platforms like eBay, Amazon, or Poshmark",
    detailedDescription:
      "Online reselling involves purchasing products at low prices and reselling them at higher prices through online marketplaces. This can include retail arbitrage, wholesale purchasing, thrift store finds, clearance items, or sourcing from manufacturers.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-4 weeks",
    startupCost: "$200-2K",
    potentialIncome: "$1K-15K+/month",
    pros: [
      "Low barrier to entry",
      "Quick cash flow potential",
      "Learn market dynamics",
      "Flexible schedule",
      "Scalable business model",
      "No specialized skills required",
    ],
    cons: [
      "Time-intensive sourcing",
      "Storage space requirements",
      "Competition pressure",
      "Seasonal demand variations",
      "Platform fee costs",
      "Inventory management challenges",
    ],
    tools: [
      "Amazon Seller App",
      "eBay",
      "Facebook Marketplace",
      "Keepa",
      "Inventory management software",
    ],
    skills: [
      "Product research",
      "Market analysis",
      "Negotiation",
      "Customer service",
      "Inventory management",
    ],
    icon: "🛒",
    marketSize: "Online resale market worth $200B+ globally",
    averageIncome: {
      beginner: "$500-2K/month",
      intermediate: "$2K-8K/month",
      advanced: "$8K-15K+/month",
    },
    userStruggles: [
      "Finding profitable products",
      "Managing storage space",
      "Dealing with returns",
      "Time-intensive sourcing",
    ],
    solutions: [
      "Use product research tools",
      "Start with online arbitrage",
      "Optimize return policies",
      "Automate where possible",
    ],
    bestFitPersonality: [
      "Enjoys hunting for deals",
      "Detail-oriented",
      "Comfortable with risk",
      "Good at pattern recognition",
    ],
    resources: {
      platforms: ["Amazon FBA", "eBay", "Poshmark", "Mercari"],
      learning: ["Reselling courses", "Arbitrage communities"],
      tools: ["Keepa", "CamelCamelCamel", "Amazon Seller App"],
    },
    actionPlan: {
      phase1: [
        "Learn product research",
        "Start with small investments",
        "Test different product categories",
        "Set up selling accounts",
      ],
      phase2: [
        "Scale successful products",
        "Optimize sourcing process",
        "Build inventory systems",
        "Expand to new platforms",
      ],
      phase3: [
        "Consider wholesale relationships",
        "Automate operations",
        "Build team for sourcing",
        "Explore private labeling",
      ],
    },
  },
  {
    id: "handmade-goods",
    name: "Handmade Goods",
    emoji: "🧶",
    description:
      "Create and sell handmade products such as crafts, jewelry, or art",
    detailedDescription:
      "Handmade goods businesses involve creating unique, handcrafted products and selling them through online platforms. This can include jewelry, clothing, home decor, art, crafts, or any custom-made items that showcase personal creativity and skill.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "2-8 weeks",
    startupCost: "$100-1K",
    potentialIncome: "$500-10K+/month",
    pros: [
      "Creative fulfillment",
      "Unique product offerings",
      "Personal brand building",
      "Flexible production schedule",
      "Premium pricing potential",
      "Direct customer relationships",
    ],
    cons: [
      "Time-intensive production",
      "Limited scalability",
      "Material cost fluctuations",
      "Seasonal demand patterns",
      "Photography and marketing needs",
      "Competition from mass production",
    ],
    tools: [
      "Etsy",
      "Shopify",
      "Canva",
      "Social media platforms",
      "Photography equipment",
    ],
    skills: [
      "Crafting expertise",
      "Photography",
      "Product design",
      "Customer service",
      "Social media marketing",
    ],
    icon: "🎨",
    marketSize: "Handmade goods market worth $44B+ globally",
    averageIncome: {
      beginner: "$200-1K/month",
      intermediate: "$1K-4K/month",
      advanced: "$4K-10K+/month",
    },
    userStruggles: [
      "Pricing products appropriately",
      "Standing out in crowded market",
      "Scaling production",
      "Managing custom orders",
    ],
    solutions: [
      "Calculate true cost including time",
      "Focus on unique value proposition",
      "Streamline production processes",
      "Set clear custom order policies",
    ],
    bestFitPersonality: [
      "Creative and artistic",
      "Detail-oriented",
      "Patient with production",
      "Enjoys working with hands",
    ],
    resources: {
      platforms: [
        "Etsy",
        "Amazon Handmade",
        "Facebook Marketplace",
        "Local craft fairs",
      ],
      learning: ["Crafting tutorials", "Etsy seller guides"],
      tools: ["Etsy", "Canva", "Instagram", "Photography lighting"],
    },
    actionPlan: {
      phase1: [
        "Perfect your craft",
        "Create initial product line",
        "Set up online store",
        "Take quality product photos",
      ],
      phase2: [
        "Build social media presence",
        "Gather customer feedback",
        "Expand product offerings",
        "Optimize pricing strategy",
      ],
      phase3: [
        "Scale production methods",
        "Consider wholesale opportunities",
        "Build brand loyalty",
        "Explore custom order services",
      ],
    },
  },
  {
    id: "amazon-fba",
    name: "Amazon FBA",
    emoji: "🏷️",
    description:
      "Sell products using Amazon's Fulfillment by Amazon (FBA) service",
    detailedDescription:
      "Amazon FBA (Fulfillment by Amazon) allows sellers to send products to Amazon's warehouses, where they handle storage, shipping, and customer service. Sellers focus on product research, sourcing, and marketing while Amazon manages the logistics. This model requires upfront investment in inventory but offers scalability and passive income potential.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "2-8 months",
    startupCost: "$1K-10K",
    potentialIncome: "$2K-50K+/month",
    pros: [
      "Amazon handles logistics",
      "Scalable business model",
      "Global reach",
      "Passive income potential",
      "Data-driven decisions",
      "Multiple product opportunities",
    ],
    cons: [
      "High upfront investment",
      "Inventory risk",
      "Amazon dependency",
      "Competitive market",
      "Complex regulations",
      "Seasonal fluctuations",
    ],
    tools: [
      "Helium 10",
      "Jungle Scout",
      "AMZScout",
      "Seller Central",
      "Keepa",
    ],
    skills: [
      "Product research",
      "Market analysis",
      "Supplier negotiation",
      "Amazon SEO",
      "Inventory management",
    ],
    icon: "🏭",
    marketSize: "Amazon marketplace worth $400B+ globally",
    averageIncome: {
      beginner: "$1K-5K/month",
      intermediate: "$5K-20K/month",
      advanced: "$20K-50K+/month",
    },
    userStruggles: [
      "Finding profitable products",
      "Managing inventory costs",
      "Competing with established sellers",
      "Understanding Amazon algorithms",
    ],
    solutions: [
      "Use research tools effectively",
      "Start with small inventory",
      "Focus on underserved niches",
      "Optimize listings for SEO",
    ],
    bestFitPersonality: [
      "Analytical and data-driven",
      "Patient with long-term results",
      "Comfortable with risk",
      "Detail-oriented",
    ],
    resources: {
      platforms: ["Amazon Seller Central", "FBA communities"],
      learning: ["Amazon Seller University", "FBA courses"],
      tools: ["Helium 10", "Jungle Scout", "Keepa"],
    },
    actionPlan: {
      phase1: [
        "Learn Amazon FBA basics",
        "Research product opportunities",
        "Find reliable suppliers",
        "Create first product listing",
      ],
      phase2: [
        "Launch first product",
        "Optimize listing and PPC",
        "Scale successful products",
        "Build supplier relationships",
      ],
      phase3: [
        "Expand product portfolio",
        "Consider private labeling",
        "Automate operations",
        "Build brand presence",
      ],
    },
  },
  {
    id: "podcasting",
    name: "Podcasting",
    emoji: "🎙️",
    description:
      "Create and monetize audio content through podcasts",
    detailedDescription:
      "Podcasting involves creating audio content on specific topics or niches, building an audience, and monetizing through sponsorships, advertising, affiliate marketing, or premium content. Successful podcasters focus on consistent content creation, audience engagement, and strategic monetization partnerships.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "6-12 months",
    startupCost: "$100-1K",
    potentialIncome: "$500-20K+/month",
    pros: [
      "Low barrier to entry",
      "Build authority in niche",
      "Multiple revenue streams",
      "Flexible schedule",
      "Global audience reach",
      "Long-term content value",
    ],
    cons: [
      "Slow audience growth",
      "Equipment and technical learning",
      "Consistent content creation needed",
      "Competition for sponsors",
      "Monetization takes time",
      "Audio quality expectations",
    ],
    tools: [
      "Anchor",
      "Audacity",
      "Zoom",
      "Canva",
      "Mailchimp",
    ],
    skills: [
      "Audio recording and editing",
      "Content planning",
      "Interview skills",
      "Marketing and promotion",
      "Audience building",
    ],
    icon: "🎙️",
    marketSize: "Podcast industry worth $4B+ and growing rapidly",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-5K/month",
      advanced: "$5K-20K+/month",
    },
    userStruggles: [
      "Building initial audience",
      "Consistent content creation",
      "Finding sponsors",
      "Technical audio quality",
    ],
    solutions: [
      "Focus on specific niche",
      "Create content calendar",
      "Network with potential sponsors",
      "Invest in quality equipment",
    ],
    bestFitPersonality: [
      "Comfortable speaking",
      "Consistent and disciplined",
      "Enjoys research and interviews",
      "Patient with growth",
    ],
    resources: {
      platforms: ["Spotify", "Apple Podcasts", "Google Podcasts"],
      learning: ["Podcasting courses", "Audio editing tutorials"],
      tools: ["Anchor", "Audacity", "Descript"],
    },
    actionPlan: {
      phase1: [
        "Choose podcast niche",
        "Set up recording equipment",
        "Create first episodes",
        "Submit to podcast directories",
      ],
      phase2: [
        "Build audience engagement",
        "Network with guests",
        "Optimize for discoverability",
        "Explore monetization options",
      ],
      phase3: [
        "Secure sponsorships",
        "Launch premium content",
        "Expand to multiple shows",
        "Build community",
      ],
    },
  },
  {
    id: "blogging",
    name: "Blogging",
    emoji: "📝",
    description:
      "Write and monetize blog content on various topics",
    detailedDescription:
      "Blogging involves creating written content on specific topics or niches, building an engaged audience, and monetizing through advertising, affiliate marketing, sponsored posts, or selling digital products. Successful bloggers focus on SEO, consistent content creation, and audience engagement.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "6-12 months",
    startupCost: "$50-500",
    potentialIncome: "$500-15K+/month",
    pros: [
      "Low startup costs",
      "Build authority and expertise",
      "Multiple monetization options",
      "Flexible work schedule",
      "SEO benefits",
      "Long-term content value",
    ],
    cons: [
      "Slow initial growth",
      "Consistent content creation needed",
      "SEO competition",
      "Monetization takes time",
      "Technical learning curve",
      "Content saturation",
    ],
    tools: [
      "WordPress",
      "Yoast SEO",
      "Mailchimp",
      "Canva",
      "Google Analytics",
    ],
    skills: [
      "Writing and editing",
      "SEO optimization",
      "Content strategy",
      "Social media marketing",
      "Email marketing",
    ],
    icon: "💡",
    marketSize: "Blogging industry worth $500M+ with growing opportunities",
    averageIncome: {
      beginner: "$0-500/month",
      intermediate: "$500-3K/month",
      advanced: "$3K-15K+/month",
    },
    userStruggles: [
      "Building initial traffic",
      "Consistent content creation",
      "SEO optimization",
      "Monetization strategy",
    ],
    solutions: [
      "Focus on specific niche",
      "Create content calendar",
      "Learn SEO fundamentals",
      "Diversify income streams",
    ],
    bestFitPersonality: [
      "Enjoys writing",
      "Patient with growth",
      "Consistent and disciplined",
      "Likes research and learning",
    ],
    resources: {
      platforms: ["WordPress", "Medium", "Substack"],
      learning: ["SEO courses", "Content marketing guides"],
      tools: ["Yoast SEO", "Google Analytics", "Mailchimp"],
    },
    actionPlan: {
      phase1: [
        "Choose blog niche",
        "Set up WordPress site",
        "Create initial content",
        "Learn basic SEO",
      ],
      phase2: [
        "Build email list",
        "Optimize for search engines",
        "Network with other bloggers",
        "Explore monetization",
      ],
      phase3: [
        "Secure sponsored posts",
        "Launch digital products",
        "Build authority",
        "Scale content production",
      ],
    },
  },
  {
    id: "consulting",
    name: "Consulting",
    emoji: "💼",
    description:
      "Provide expert advice and solutions to businesses or individuals",
    detailedDescription:
      "Consulting involves providing expert advice and strategic guidance to businesses in your area of expertise. Consultants help clients solve problems, improve processes, and achieve goals through specialized knowledge and experience. This can include business strategy, operations, marketing, technology, or industry-specific consulting.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "2-8 months",
    startupCost: "$0-2K",
    potentialIncome: "$5K-50K+/month",
    pros: [
      "High hourly rates",
      "Leverage existing expertise",
      "Flexible client base",
      "Intellectual challenge",
      "Build reputation",
      "Scalable through products",
    ],
    cons: [
      "Time-for-money limitation",
      "Client acquisition challenges",
      "Requires proven expertise",
      "Project-based income",
      "High client expectations",
      "Travel requirements",
    ],
    tools: [
      "Zoom",
      "Slack",
      "Notion",
      "PowerPoint",
      "Stripe",
    ],
    skills: [
      "Deep expertise in specific area",
      "Problem-solving",
      "Communication and presentation",
      "Project management",
      "Client relationship management",
    ],
    icon: "🧑‍💼",
    marketSize: "Consulting industry worth $250B+ globally",
    averageIncome: {
      beginner: "$2K-8K/month",
      intermediate: "$8K-25K/month",
      advanced: "$25K-50K+/month",
    },
    userStruggles: [
      "Establishing credibility",
      "Finding initial clients",
      "Pricing services appropriately",
      "Managing client expectations",
    ],
    solutions: [
      "Build strong case studies",
      "Network actively",
      "Start with lower rates",
      "Set clear project scope",
    ],
    bestFitPersonality: [
      "Expert in specific field",
      "Strong communication skills",
      "Problem-solving mindset",
      "Professional and trustworthy",
    ],
    resources: {
      platforms: ["LinkedIn", "Consulting communities"],
      learning: ["Industry certifications", "Consulting courses"],
      tools: ["Zoom", "Notion", "Stripe"],
    },
    actionPlan: {
      phase1: [
        "Identify your expertise",
        "Create consulting packages",
        "Build professional presence",
        "Network with potential clients",
      ],
      phase2: [
        "Deliver first projects",
        "Collect testimonials",
        "Refine service offerings",
        "Build referral network",
      ],
      phase3: [
        "Increase rates",
        "Create scalable products",
        "Build team",
        "Focus on premium clients",
      ],
    },
  },
  {
    id: "real-estate-investing",
    name: "Real Estate Investing",
    emoji: "🏠",
    description:
      "Invest in and manage real estate properties for profit",
    detailedDescription:
      "Real estate investing involves purchasing properties to generate income through rentals, appreciation, or flipping. This can include residential rentals, commercial properties, house flipping, or real estate crowdfunding. Success requires market knowledge, financial analysis, and property management skills.",
    fitScore: 0,
    difficulty: "Hard",
    timeToProfit: "6-24 months",
    startupCost: "$10K-100K+",
    potentialIncome: "$2K-50K+/month",
    pros: [
      "Tangible asset ownership",
      "Multiple income streams",
      "Tax benefits",
      "Appreciation potential",
      "Leverage opportunities",
      "Passive income",
    ],
    cons: [
      "High capital requirements",
      "Market risk",
      "Property management challenges",
      "Illiquid investment",
      "Maintenance costs",
      "Regulatory complexity",
    ],
    tools: [
      "Zillow",
      "BiggerPockets",
      "RentSpree",
      "QuickBooks",
      "Cozy",
    ],
    skills: [
      "Market analysis",
      "Financial modeling",
      "Property evaluation",
      "Negotiation",
      "Property management",
    ],
    icon: "🏠",
    marketSize: "Real estate market worth $3.7T+ in the US alone",
    averageIncome: {
      beginner: "$1K-5K/month",
      intermediate: "$5K-20K/month",
      advanced: "$20K-50K+/month",
    },
    userStruggles: [
      "High capital requirements",
      "Finding good deals",
      "Property management",
      "Market timing",
    ],
    solutions: [
      "Start with REITs or crowdfunding",
      "Network with real estate professionals",
      "Hire property managers",
      "Focus on cash flow over appreciation",
    ],
    bestFitPersonality: [
      "Analytical and research-oriented",
      "Comfortable with large investments",
      "Patient with long-term results",
      "Good at networking",
    ],
    resources: {
      platforms: ["BiggerPockets", "Real estate investment groups"],
      learning: ["Real estate courses", "Market analysis training"],
      tools: ["Zillow", "RentSpree", "QuickBooks"],
    },
    actionPlan: {
      phase1: [
        "Learn real estate fundamentals",
        "Analyze local markets",
        "Build investment criteria",
        "Network with professionals",
      ],
      phase2: [
        "Make first investment",
        "Learn property management",
        "Build team of professionals",
        "Scale portfolio",
      ],
      phase3: [
        "Diversify property types",
        "Consider commercial properties",
        "Build passive income streams",
        "Explore new markets",
      ],
    },
  },
  {
    id: "online-course-creation",
    name: "Online Course Creation",
    emoji: "🎓",
    description:
      "Create and sell online courses on platforms like Udemy or Teachable",
    detailedDescription:
      "Online course creation involves developing educational content on specific topics and selling it through platforms like Udemy, Teachable, or your own website. Successful course creators focus on solving specific problems, creating engaging content, and building a marketing system to reach their target audience.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "2-12 months",
    startupCost: "$100-2K",
    potentialIncome: "$1K-50K+/month",
    pros: [
      "Scalable income",
      "Leverage existing knowledge",
      "Passive income potential",
      "Global reach",
      "Build authority",
      "Multiple revenue streams",
    ],
    cons: [
      "High initial time investment",
      "Competitive market",
      "Technical learning curve",
      "Marketing required",
      "Content updates needed",
      "Platform dependency",
    ],
    tools: [
      "Teachable",
      "Camtasia",
      "Loom",
      "Canva",
      "Mailchimp",
    ],
    skills: [
      "Subject matter expertise",
      "Content creation",
      "Video production",
      "Instructional design",
      "Marketing and sales",
    ],
    icon: "🎓",
    marketSize: "Online education market worth $350B+ globally",
    averageIncome: {
      beginner: "$500-3K/month",
      intermediate: "$3K-15K/month",
      advanced: "$15K-50K+/month",
    },
    userStruggles: [
      "Creating engaging content",
      "Marketing courses effectively",
      "Standing out in crowded market",
      "Technical production quality",
    ],
    solutions: [
      "Focus on specific problems",
      "Build email list before launch",
      "Create unique value proposition",
      "Invest in quality equipment",
    ],
    bestFitPersonality: [
      "Enjoys teaching others",
      "Patient with content creation",
      "Comfortable on camera",
      "Organized and systematic",
    ],
    resources: {
      platforms: ["Teachable", "Udemy", "Kajabi"],
      learning: ["Course creation courses", "Video production tutorials"],
      tools: ["Camtasia", "Loom", "Canva"],
    },
    actionPlan: {
      phase1: [
        "Identify course topic",
        "Research target audience",
        "Create course outline",
        "Set up course platform",
      ],
      phase2: [
        "Record course content",
        "Build email list",
        "Create marketing materials",
        "Launch beta version",
      ],
      phase3: [
        "Gather student feedback",
        "Optimize course content",
        "Scale marketing efforts",
        "Create additional courses",
      ],
    },
  },
  {
    id: "ghostwriting",
    name: "Ghostwriting",
    emoji: "👻",
    description:
      "Write content for others who are credited as the author",
    detailedDescription:
      "Ghostwriting involves writing content for others who publish under their own name. This can include books, articles, speeches, blog posts, and other content. Ghostwriters must adapt their writing style to match their client's voice while maintaining high quality and meeting deadlines.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "2-8 months",
    startupCost: "$0-300",
    potentialIncome: "$3K-30K+/month",
    pros: [
      "High project rates",
      "Diverse content types",
      "Build relationships",
      "Learn from experts",
      "Flexible schedule",
      "Portfolio variety",
    ],
    cons: [
      "No public credit",
      "Client dependency",
      "Confidentiality requirements",
      "Project-based income",
      "Client management",
      "Style adaptation",
    ],
    tools: [
      "Google Docs",
      "Scrivener",
      "Zoom",
      "Trello",
      "PayPal",
    ],
    skills: [
      "Adaptable writing style",
      "Research capabilities",
      "Interview skills",
      "Project management",
      "Client collaboration",
    ],
    icon: "👻",
    marketSize: "Ghostwriting industry worth $500M+ with growing demand",
    averageIncome: {
      beginner: "$1K-5K/month",
      intermediate: "$5K-15K/month",
      advanced: "$15K-30K+/month",
    },
    userStruggles: [
      "Finding quality clients",
      "Adapting writing style",
      "Managing multiple projects",
      "Building trust with clients",
    ],
    solutions: [
      "Build strong portfolio",
      "Practice style adaptation",
      "Use project management tools",
      "Maintain confidentiality",
    ],
    bestFitPersonality: [
      "Adaptable writer",
      "Collaborative worker",
      "Maintains confidentiality",
      "Strong communication skills",
    ],
    resources: {
      platforms: ["Upwork", "LinkedIn", "Ghostwriting agencies"],
      learning: ["Writing courses", "Style adaptation training"],
      tools: ["Scrivener", "Google Docs", "Trello"],
    },
    actionPlan: {
      phase1: [
        "Build writing portfolio",
        "Identify target clients",
        "Set up professional presence",
        "Network with potential clients",
      ],
      phase2: [
        "Secure first projects",
        "Develop client relationships",
        "Refine writing process",
        "Build referral network",
      ],
      phase3: [
        "Increase project rates",
        "Focus on premium clients",
        "Create scalable processes",
        "Consider team expansion",
      ],
    },
  },
  {
    id: "e-commerce",
    name: "E-Commerce",
    emoji: "🛒",
    description:
      "Sell products through online stores or marketplaces",
    detailedDescription:
      "E-commerce involves building and selling products through your own online store. This gives you full control over branding, customer experience, and business operations. E-commerce businesses can sell physical products, digital products, or services through platforms like Shopify, WooCommerce, or custom websites.",
    fitScore: 0,
    difficulty: "Medium",
    timeToProfit: "2-12 months",
    startupCost: "$500-10K",
    potentialIncome: "$2K-100K+/month",
    pros: [
      "Full business control",
      "Brand building",
      "Scalable model",
      "Multiple revenue streams",
      "Customer data ownership",
      "Global reach",
    ],
    cons: [
      "High upfront investment",
      "Inventory management",
      "Customer service demands",
      "Marketing costs",
      "Technical complexity",
      "Competition",
    ],
    tools: [
      "Shopify",
      "WooCommerce",
      "Mailchimp",
      "Google Analytics",
      "Canva",
    ],
    skills: [
      "Product development",
      "Brand building",
      "Website management",
      "Digital marketing",
      "Customer service",
    ],
    icon: "🛒",
    marketSize: "E-commerce market worth $5T+ globally",
    averageIncome: {
      beginner: "$1K-5K/month",
      intermediate: "$5K-25K/month",
      advanced: "$25K-100K+/month",
    },
    userStruggles: [
      "Product development",
      "Customer acquisition",
      "Inventory management",
      "Competition with large retailers",
    ],
    solutions: [
      "Focus on unique products",
      "Build strong brand identity",
      "Use inventory management tools",
      "Create excellent customer experience",
    ],
    bestFitPersonality: [
      "Product-focused mindset",
      "Brand building interest",
      "Comfortable with technology",
      "Customer service oriented",
    ],
    resources: {
      platforms: ["Shopify", "WooCommerce", "Amazon"],
      learning: ["E-commerce courses", "Digital marketing training"],
      tools: ["Shopify", "Mailchimp", "Google Analytics"],
    },
    actionPlan: {
      phase1: [
        "Research product opportunities",
        "Choose e-commerce platform",
        "Set up online store",
        "Launch first products",
      ],
      phase2: [
        "Optimize website conversion",
        "Implement marketing strategies",
        "Build customer base",
        "Expand product line",
      ],
      phase3: [
        "Scale operations",
        "Explore new markets",
        "Build brand authority",
        "Consider acquisitions",
      ],
    },
  },
  {
    id: "dropshipping",
    name: "Dropshipping",
    emoji: "🚚",
    description:
      "Sell products online without holding inventory, using suppliers to fulfill orders",
    detailedDescription:
      "Dropshipping involves selling products online without holding inventory. You partner with suppliers who ship products directly to your customers when orders are placed. This model requires strong marketing skills, product research, and customer service, but eliminates inventory management and upfront costs.",
    fitScore: 0,
    difficulty: "Easy",
    timeToProfit: "1-4 months",
    startupCost: "$100-2K",
    potentialIncome: "$1K-20K+/month",
    pros: [
      "Low upfront investment",
      "No inventory management",
      "Easy to start",
      "Multiple product testing",
      "Location independence",
      "Scalable model",
    ],
    cons: [
      "Lower profit margins",
      "Supplier dependency",
      "Customer service challenges",
      "Shipping delays",
      "Quality control issues",
      "High competition",
    ],
    tools: [
      "Shopify",
      "Oberlo",
      "AliExpress",
      "Facebook Ads",
      "Google Analytics",
    ],
    skills: [
      "Product research",
      "Digital marketing",
      "Customer service",
      "Website management",
      "Analytics understanding",
    ],
    icon: "📦",
    marketSize: "Dropshipping market worth $200B+ globally",
    averageIncome: {
      beginner: "$500-3K/month",
      intermediate: "$3K-10K/month",
      advanced: "$10K-20K+/month",
    },
    userStruggles: [
      "Finding profitable products",
      "Managing customer expectations",
      "Dealing with shipping delays",
      "Standing out in competition",
    ],
    solutions: [
      "Use product research tools",
      "Set clear shipping expectations",
      "Work with reliable suppliers",
      "Focus on unique marketing angles",
    ],
    bestFitPersonality: [
      "Marketing-focused",
      "Product research oriented",
      "Comfortable with risk",
      "Customer service minded",
    ],
    resources: {
      platforms: ["Shopify", "WooCommerce", "Amazon"],
      learning: ["Dropshipping courses", "Digital marketing training"],
      tools: ["Oberlo", "AliExpress", "Facebook Ads"],
    },
    actionPlan: {
      phase1: [
        "Research product opportunities",
        "Set up online store",
        "Find reliable suppliers",
        "Launch first products",
      ],
      phase2: [
        "Implement marketing strategies",
        "Optimize conversion rates",
        "Scale successful products",
        "Build customer base",
      ],
      phase3: [
        "Expand product portfolio",
        "Consider private labeling",
        "Build brand presence",
        "Explore new markets",
      ],
    },
  },
];
